# Generated by Django 3.2.3 on 2021-05-28 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de la categoria')),
                ('nom_cat', models.CharField(max_length=50, verbose_name='nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de la marca')),
                ('nom_mar', models.CharField(max_length=50, verbose_name='nombre de la marca')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del producto')),
                ('n_producto', models.CharField(max_length=100, verbose_name='nombre del producto')),
                ('stock', models.IntegerField(verbose_name='stock del producto')),
                ('precio', models.IntegerField(verbose_name='precio del producto')),
                ('valoracion', models.IntegerField(verbose_name='valoracion del producto')),
                ('sku', models.IntegerField(verbose_name='codigo sku del producto')),
                ('des_pro', models.CharField(max_length=200, verbose_name='descripcion del producto')),
                ('color_pro', models.CharField(max_length=20, verbose_name='color del producto')),
                ('foto_pro', models.CharField(max_length=20, verbose_name='foto del producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.marca')),
            ],
        ),
    ]
