# Generated by Django 3.2.3 on 2021-05-31 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del carrito')),
                ('f_comp', models.DateField(verbose_name='Fecha de la compra')),
                ('id_direccion_c', models.CharField(blank=True, max_length=100, verbose_name='direccion de la compra')),
                ('status', models.IntegerField(verbose_name='status del carrito')),
                ('total_pre', models.IntegerField(verbose_name='total del precio producto')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la comuna')),
                ('nombre_comuna', models.CharField(max_length=100, verbose_name='Nombre comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del contacto')),
                ('p_nombre', models.CharField(max_length=100, verbose_name='primer nombre')),
                ('s_nombre', models.CharField(max_length=100, verbose_name='segundo nombre')),
                ('correo_con', models.CharField(max_length=100, verbose_name='correo del contacto')),
                ('telefono', models.CharField(max_length=11, verbose_name='telefono del contacto')),
                ('comentario', models.CharField(max_length=200, verbose_name='comentario del contacto')),
                ('status_con', models.IntegerField(verbose_name='status del comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la region')),
                ('nombre_region', models.CharField(max_length=100, verbose_name='Nombre region')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id_usu_tip', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del usuario')),
                ('nom_usu', models.CharField(max_length=50, verbose_name='Tipo de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del contacto')),
                ('nombre_u', models.CharField(max_length=100, verbose_name='nombre usuario')),
                ('apellido_u', models.CharField(max_length=100, verbose_name='apellido usuario')),
                ('email_u', models.CharField(max_length=100, verbose_name='correo del usuario')),
                ('telofono_u', models.CharField(max_length=11, verbose_name='telefono del usuario')),
                ('contraseña_u', models.CharField(max_length=20, verbose_name='comentario del usuario')),
                ('run_u', models.IntegerField(verbose_name='run del usuario')),
                ('dv_run', models.CharField(max_length=1, verbose_name='digito verificador del usuario')),
                ('cod_post', models.IntegerField(verbose_name='codigo postal del usuario')),
                ('modo_osc', models.IntegerField(verbose_name='modo oscuro/modo normal')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Pro_carrito',
            fields=[
                ('id_pro_carr', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del producto en el carrito')),
                ('canti_pro', models.IntegerField(verbose_name='cantidad de productos')),
                ('sub_total', models.IntegerField(verbose_name='sub total')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la direccion')),
                ('descrip_dir', models.CharField(max_length=100, verbose_name='Descripcion de la direccion')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.comuna')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.usuario'),
        ),
    ]
