# Generated by Django 3.2.3 on 2021-06-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_auto_20210601_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido_u',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='dv_run',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_u',
        ),
        migrations.AddField(
            model_name='usuario',
            name='alias',
            field=models.CharField(blank=True, max_length=200, verbose_name='nombre de usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=200, verbose_name='nombre completo de la persona'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='modo_osc',
            field=models.IntegerField(blank=True, verbose_name='modo oscuro/modo normal'),
        ),
    ]
