# Generated by Django 3.2.3 on 2021-06-01 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_auto_20210601_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.region'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='alias',
            field=models.CharField(max_length=200, verbose_name='nombre de usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(max_length=200, verbose_name='nombre completo de la persona'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.tipo_usuario'),
        ),
    ]
