# Generated by Django 3.2.3 on 2021-06-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_auto_20210601_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto_pro',
            field=models.ImageField(upload_to='producto'),
        ),
    ]
