# Generated by Django 3.2.3 on 2021-06-23 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_alter_producto_foto_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la venta')),
                ('fecha_venta', models.DateField(verbose_name='fecha de la venta')),
                ('total_venta', models.IntegerField(verbose_name='total de la venta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_venta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del detalle de la venta')),
                ('cantidad_sub', models.IntegerField(verbose_name='cantidad subtotal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.venta')),
            ],
        ),
    ]
