# Generated by Django 3.2.3 on 2021-07-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0009_alter_producto_foto_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto_pro',
            field=models.ImageField(upload_to='producto'),
        ),
    ]
